[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.28"
evm_version = "cancun" 
optimizer = true
optimizer_runs = 200
via_ir = true
fs_permissions = [
    { access = "read", path = "./" },
    { access = "write", path = "./deployments" }
]

remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/"
]

# RPC Endpoints
[rpc_endpoints]
bsc = "https://bsc-dataseed.binance.org/"
bsc_testnet = "https://bsc-testnet.infura.io/v3/YOUR_INFURA_API_KEY"
sepolia = "https://sepolia.infura.io/v3/YOUR_INFURA_API_KEY"

# Block Explorer API Keys
[etherscan]
bsc = { key = "${BSCSCAN_API_KEY}", chain = 56 }
bsc_testnet = { key = "${BSCSCAN_API_KEY}", chain = 97 }
sepolia = { key = "${ETHERSCAN_API_KEY}", chain = 11155111 }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
